### ISSUE TITLE
Query CSV does not work : it tries to parse JSON even if CSV output is specified

### ISSUE THREAD

**Issue by going-striker** [AvapiDotNet/Avapi#5]
Hi

First of all thanks for the work.

Issue is quite simple and described in the title

```
			// Sent the Request and get the raw data from the Response
			string response = RestClient?.
				GetAsync(queryString)?.
				Result?.
				Content?.
				ReadAsStringAsync()?.
				Result; 

			IAvapiResponse_TIME_SERIES_DAILY ret = new AvapiResponse_TIME_SERIES_DAILY
			{
				RawData = response,
				Data = ParseInternal(response),
				LastHttpRequest = queryString
			};
			// Sent the Request and get the raw data from the Response
			string response = RestClient?.
				GetAsync(queryString)?.
				Result?.
				Content?.
				ReadAsStringAsync()?.
				Result; 

			IAvapiResponse_TIME_SERIES_DAILY ret = new AvapiResponse_TIME_SERIES_DAILY
			{
				RawData = response,
				Data = ParseInternal(response),
				LastHttpRequest = queryString
			};
```

The ParseInternal method does JSON serialization but there is no condition about the output.

Not blocking, I can query JSON and get the data, but perhaps it would be better to prevent CSV calls in that case instead of letting API calls that will throw an exception

Thks & rgds

**Comment by sgiulians** [comment]
Spot on!  I will generate the new code soon (without csv option) and will release the new version.
Thanks!

**Comment by sgiulians** [comment]
Released new version without data_type. Json will be the only one supported for now:
https://www.nuget.org/packages/Avapi/1.4.8.1

Have a good day
