### ISSUE TITLE
Adding NuGet package generates all classes inside project

### ISSUE THREAD

**Issue by motek80** [AvapiDotNet/Avapi#6]
I just added Avapi package to my project (VS 2017, regular .NET project).

While adding package, its script started to generate dozens of classes inside my project, adding tones of garbage. Also, after that compilation produces thousands of warnings, telling that it has duplicates of everything (one copy declared in assembly and another everything generated in project).

As now, in my opinion nuget package is not usable.

**Comment by sgiulians** [comment]
Ciao motek,
I am gonna upgrade to VS2017 (I was on VS2015) and see what happens. 
We use indeed generative programming to create the classes but you shouldn't see any garbage in the dependency folder. In the meantime could you please more specific about the warnings you are getting?

Thanks

**Comment by motek80** [comment]
It looks like package installation generates exactly the same classes as located in assembly. Therefore, during compilation warning issued about having classes with same name in two different assemblies.

**Comment by sgiulians** [comment]
Hi motek,
I have changed the csproj accordingly and the problem should have been fixed in the new version (**1.4.8.2**). It has just been released (it's not indexed yet on nuget but it will be in few hours I guess). Thanks for spotting the issue, let me know if you find others.

Simone
