### ISSUE TITLE
Multiple queries in succession, throws null reference exception

### ISSUE THREAD

**Issue by Cpt-Falcon** [AvapiDotNet/Avapi#9]
I'm trying to use like 15 queries in a row in succession, and i'm getting a random, non deterministic null reference exception in visual studio 2017 C#.

For example, just a few lines of code

 var timeQueryObject = this.connection.GetQueryObject_TIME_SERIES_DAILY();
            IAvapiResponse_TIME_SERIES_DAILY timeSeriesDailyResponse = timeQueryObject.Query(symbol, Const_TIME_SERIES_DAILY.TIME_SERIES_DAILY_outputsize.compact);

            var smaQueryObject = this.connection.GetQueryObject_SMA();
            IAvapiResponse_SMA avapiResponseSMA = smaQueryObject.Query(symbol, Avapi.AvapiSMA.Const_SMA.SMA_interval.weekly, 60, Avapi.AvapiSMA.Const_SMA.SMA_series_type.close);

            var emaQuaryObject = this.connection.GetQueryObject_EMA();
            IAvapiResponse_EMA avapiResponseEMA = emaQuaryObject.Query(symbol, Const_EMA.EMA_interval.weekly, 60, Const_EMA.EMA_series_type.close);

            var wmaQuaryObject = this.connection.GetQueryObject_WMA();
            IAvapiResponse_WMA avapiResponseWMA = wmaQuaryObject.Query(symbol, Const_WMA.WMA_interval.weekly, 60, Const_WMA.WMA_series_type.close);

One of these is likely to throw a null reference exception. For now I am just going to loop over each one until there is no exception but that's not a very elegant solution. I could investigate this in the repo if you would like.

**Comment by sgiulians** [comment]
Hey hello,
You can indeed investigate. I am generally happy to merge pull request..
Please, when it doesn't work could you please log the RawData of the response? It must be an unexpected non-well formed response. 
Cheers

**Comment by Cpt-Falcon** [comment]
Thanks for your response:

 I have determined that the problem is here:

// Sent the Request and get the raw data from the Response
			string response = RestClient?.
				GetAsync(queryString)?.
				Result?.
				Content?.
				ReadAsStringAsync()?.
				Result; 

			IAvapiResponse_AD ret = new AvapiResponse_AD
			{
				RawData = response,
				Data = ParseInternal(response),
				LastHttpRequest = queryString
			};

A null reference exception is thrown when you make more than 5 calls per minute under the free key and the parse method fails because you get this response back:

{
    "Note": "Thank you for using Alpha Vantage! Our standard API call frequency is 5 calls per minute and 500 calls per day. Please visit https://www.alphavantage.co/premium/ if you would like to target a higher API call frequency."
}

So the request is malformed in the sense that its not expected. I fixed this problem by simply adding a 1 minute delay after 5 calls and that was just due to my ignorance about the limitations of the free key but it would probably be prudent to add some verification. I can add a regex to check if the first element is a note and then maybe return some kind of error message in the data.

**Comment by sgiulians** [comment]
Spot on! Thanks serp! When this wrapper has been developed, there wasn't a premium version of Alpha Vantage. Returning an error message is the best solution but please don't add a regex. If you have noticed, in the source code there is a folder for each operation. In the *_Impl files there's a method called ParseInternal, we should add something there (check the presence of Note) and set the error message as you said in your previous post. Once we are happy with the change we must change the Alpha Vantage generator here: https://github.com/AvapiDotNet/Avapi/blob/master/tools/AvapiGenerator/Implementation.cs.
We will run the generator and then the new parsing will be picked up by all the operation.
Can you do that?  If you have any problems give a shout, we'll go through it..
